OnlineBookShopMvc/Models/Cart.cs
using Microsoft.EntityFrameworkCore;
using OnlineBookShopMvc.Data;

namespace OnlineBookShopMvc.Models
{
    public class Cart
    {
        private readonly BookShopDbContext _context;
        public Cart(BookShopDbContext context)
        {
            _context = context;
        }

        public string Id { get; set; }
        public List<CartItem> CartItems { get; set; }
        public static Cart GetCart(IServiceProvider service)
        {
            ISession session = service.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = service.GetService<BookShopDbContext>();

            string cartId = session.GetString("Id")??Guid.NewGuid().ToString();
            session.SetString("Id", cartId);

            return new Cart(context) { Id = cartId };
        }

        public List<CartItem> GetAllCartItem()
        {
            return CartItems ??(_context.CartItems
                .Where(ci => ci.CardId == Id)
                .Include(ci => ci.Book)
                .ToList());
        }
        public decimal GetCartTotal()
        {
            return _context.CartItems
                .Where(ci => ci.CardId == Id)
                .Select(ci => ci.Quantity * (ci.Book.Price - (ci.Book.Discount * ci.Book.Price)/100))
                .Sum(); 
        }
        public CartItem GetCartItem(Book book)
        {
            return _context.CartItems.SingleOrDefault(ci => 
                ci.Book.Id == book.Id && ci.CardId == Id);
        }

        public void AddToCart(Book book, int quantity)
        {
            var cartItem = GetCartItem(book);
            if(cartItem == null) 
            {
                cartItem = new CartItem
                {
                    Id = Guid.NewGuid().ToString(),
                    Book = book,
                    Quantity = quantity,
                    CardId = Id
                };
                _context.CartItems.Add(cartItem);
            }
            else
            {
                cartItem.Quantity += quantity;
            }
            _context.SaveChanges();

        }

        public int ReduceQuantity(Book book)
        {
            var cartItem = GetCartItem(book);
            var remainingQuantity = 0;
            if(cartItem != null ) 
            { 
                if(cartItem.Quantity > 1)
                {
                    remainingQuantity = --cartItem.Quantity;
                }
                else
                {
                    _context.CartItems.Remove(cartItem);
                }
            }
            _context.SaveChanges();
            return remainingQuantity;
        }
		public int IncreaseQuantity(Book book)
		{
			var cartItem = GetCartItem(book);
			var remainingQuantity = 0;
			if (cartItem != null)
			{
				if (cartItem.Quantity > 0)
				{
					remainingQuantity = ++cartItem.Quantity;
				}
				
			}
			_context.SaveChanges();
			return remainingQuantity;
		}
	    public void RemoveFromCart(Book book)
        {
            var cartItem = GetCartItem(book);
            if (cartItem != null)
            {
                _context.CartItems.Remove(cartItem);
            }
            _context.SaveChanges();
        }

        public void ClearCart()
        {
            var cartItems = _context.CartItems.Where(ci => ci.CardId == Id);

            _context.CartItems.RemoveRange(cartItems);

            _context.SaveChanges();
        }
    }
}

OnlineBookShopMvc/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineBookShopMvc.Data;
using OnlineBookShopMvc.Models;
using System.Reflection.Metadata;

namespace OnlineBookShopMvc.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly Cart _cart;
        private readonly BookShopDbContext _context;
        public CartController(Cart cart, BookShopDbContext context)
        {
            _cart = cart;
            _context = context;
        }

        public IActionResult Index()
        {
            var items = _cart.GetAllCartItem();
            _cart.CartItems = items;
            return View(_cart);
        }
        public IActionResult AddToCart(Guid id)
        {
            var selectedBook = GetBookById(id);

            if(selectedBook != null)
            {
                _cart.AddToCart(selectedBook,quantity: 1);
            }

            return RedirectToAction("Index", "Store");
        }

        public Book GetBookById(Guid id)
        {
            return _context.Books.FirstOrDefault(x => x.Id == id);
        }

        public IActionResult RemoveFromCart(Guid id)
        {
            var selectedBook = GetBookById(id);

            if(selectedBook != null)
            {
                _cart.RemoveFromCart(selectedBook);
            }
            return RedirectToAction("Index");
        }

        public IActionResult ReduceQuantity(Guid id) 
        {
            var selectedBook = GetBookById(id);
            if(selectedBook != null)
            {
                _cart.ReduceQuantity(selectedBook);
            }
            return RedirectToAction("Index");
        }
		public IActionResult IncreaseQuantity(Guid id)
		{
			var selectedBook = GetBookById(id);
			if (selectedBook != null)
			{
				_cart.IncreaseQuantity(selectedBook);
			}
			return RedirectToAction("Index");
		}
        public IActionResult ClearCart()
        {
            _cart.ClearCart();
            return RedirectToAction("Index");
        }
	}
}

OnlineBookShopMvc/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineBookShopMvc.Data;
using OnlineBookShopMvc.Models;

namespace OnlineBookShopMvc.Controllers;

[Authorize]
public class OrderController : Controller
{
	private readonly BookShopDbContext _context;
	private readonly Cart _cart;

	public OrderController(BookShopDbContext context, Cart cart)
	{
		_context = context;
		_cart = cart;
	}

	public IActionResult Checkout()
	{
		return View();
	}

	[HttpPost]
	public IActionResult Checkout(Order order)
	{
		var cartItems = _cart.GetAllCartItem();
		_cart.CartItems = cartItems;

		if(_cart.CartItems.Count == 0) 
		{
			ModelState.AddModelError("", "cart is empty please add a book first");
		}

		if (ModelState.IsValid)
		{
			CreateOrder(order);
			_cart.ClearCart();
			return View("CheckoutComplete", order);	
		}
		return View(order);
	}

	public IActionResult CheckoutComplete(Order order)
	{
		return View(order);
	}
	public void CreateOrder(Order order)
	{
		order.OrderPlacedAt= DateTime.Now;

		var cartItems = _cart.CartItems;

		foreach (var item in cartItems)
		{
			var orderItem = new OrderItem()
			{
				Quantity = item.Quantity,
				BookId = item.Book.Id,
				OrderId = order.Id,
				Price = (item.Book.Price - (item.Book.Price * item.Book.Discount / 100)) * item.Quantity
			};
			order.OrderItems.Add(orderItem);
			order.OrderTotal += orderItem.Price;
		}
		_context.Orders.Add(order);
		_context.SaveChanges();

	}
}

OnlineBookShopMvc/Views/Cart/Index.cshtml
@model OnlineBookShopMvc.Models.Cart;


<h1>Cart</h1>

@if(Model.CartItems.Count > 0){
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th>Book</th>
				<th>Discount</th>
				<th>Price  | Over all price</th>
				<th>Quantity</th>
				<th>Remove</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.CartItems)
			{
				var bookTotalPrice = item.Book.Price * item.Quantity;
				var bookTotalPriceDiscount = (item.Book.Price - (item.Book.Price * item.Book.Discount / 100)) * item.Quantity;
				<tr>
					<td>
						<a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.Id"><img src="@item.Book.ImageUrl" style="height: 4em"> </a>
					</td>
					<td>
						<a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.Id">@item.Book.Name</a>
					</td>
					<td>
						@item.Book.Discount %
					</td>
					<td>
						@bookTotalPrice.ToString() | @bookTotalPriceDiscount.ToString();
					</td>
					<td>
						<a asp-controller="Cart" asp-action="ReduceQuantity" asp-route-id="@item.Book.Id"><i class="fa-solid fa-minus"></i></a>
						<span class="btn">@item.Quantity</span> 
						<a asp-controller="Cart" asp-action="IncreaseQuantity" asp-route-id="@item.Book.Id"><i class="fa-solid fa-plus"></i></a>
					</td>
					<td>
						<a asp-controller="Cart" asp-action="RemoveFromCart" asp-route-id="@item.Book.Id" class="text-danger"><i class="fa-solid fa-xmark"></i></a>
					</td>

				</tr>
			}
		</tbody>
		<tfoot>
			<td></td>
			<td class="text-right">
				<strong>
					Total
				</strong>
			</td>
			<td>
				<strong>
					@Model?.GetCartTotal().ToString("c")
				</strong>
			</td>

		</tfoot>
	</table>
		<a class="a-cleanup" asp-controller="Order" asp-action="Checkout">
			<div class="btn btn-success float-right mr-5">
				<i class="fa-solid fa-angles-right"></i>
			</div>
		</a>
		<a class="a-cleanup" asp-controller="Cart" asp-action="ClearCart">
			<div class="btn btn-primary float-end mr-5">
				<i class="fa-solid fa-trash"></i>
			</div>
		</a>
}
else{
	<h3 class="text-center">Cart is empty</h3>
}