OnlineBookShopMvc/Models/Order.cs
namespace OnlineBookShopMvc.Models
{
	public class Order
	{
		public Guid Id { get; set; }
		public List<OrderItem> OrderItems { get; set; } = new();
		public decimal OrderTotal { get; set; }
		public DateTime OrderPlacedAt { get; set; }
	}
}

OnlineBookShopMvc/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineBookShopMvc.Data;
using OnlineBookShopMvc.Models;

namespace OnlineBookShopMvc.Controllers;

[Authorize]
public class OrderController : Controller
{
	private readonly BookShopDbContext _context;
	private readonly Cart _cart;

	public OrderController(BookShopDbContext context, Cart cart)
	{
		_context = context;
		_cart = cart;
	}

	public IActionResult Checkout()
	{
		return View();
	}

	[HttpPost]
	public IActionResult Checkout(Order order)
	{
		var cartItems = _cart.GetAllCartItem();
		_cart.CartItems = cartItems;

		if(_cart.CartItems.Count == 0) 
		{
			ModelState.AddModelError("", "cart is empty please add a book first");
		}

		if (ModelState.IsValid)
		{
			CreateOrder(order);
			_cart.ClearCart();
			return View("CheckoutComplete", order);	
		}
		return View(order);
	}

	public IActionResult CheckoutComplete(Order order)
	{
		return View(order);
	}
	public void CreateOrder(Order order)
	{
		order.OrderPlacedAt= DateTime.Now;

		var cartItems = _cart.CartItems;

		foreach (var item in cartItems)
		{
			var orderItem = new OrderItem()
			{
				Quantity = item.Quantity,
				BookId = item.Book.Id,
				OrderId = order.Id,
				Price = (item.Book.Price - (item.Book.Price * item.Book.Discount / 100)) * item.Quantity
			};
			order.OrderItems.Add(orderItem);
			order.OrderTotal += orderItem.Price;
		}
		_context.Orders.Add(order);
		_context.SaveChanges();

	}
}

OnlineBookShopMvc/Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineBookShopMvc.Data;

namespace OnlineBookShopMvc.Controllers
{
    [Authorize]
    public class StoreController : Controller
    {
        private readonly BookShopDbContext _context;
        public StoreController(BookShopDbContext context)
        {
            _context = context;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchString, string minPrice, string maxPrice)
        {
            var books = _context.Books.Include(b => b.Author).Include(b => b.Category).AsQueryable();
            if(!string.IsNullOrEmpty(searchString) ) 
            {
                books = books.Where(b => b.Name.Contains(searchString) || b.Author.FirstName.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(minPrice))
            {
                var min = int.Parse(minPrice);

                books = books.Where(b => b.Price >= min);
            }
            if (!string.IsNullOrEmpty(maxPrice))
            {
                var max = int.Parse(maxPrice);

                books = books.Where(b => b.Price <= max);
            }
            return View(await books.ToListAsync());
        }
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
    }
}

OnlineBookShopMvc/Views/Order/Checkout.cshtml
@model Order
<form asp-action="Checkout" method="post" class="form horizontal" role="form">
	<h4>please confirm yuuor purchase</h4>
	<div asp-validation-summary="All" class="text-danger"></div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-5">
			<input type="submit" class="btn btn-primary" value="Complete Order"/>
		</div>

	</div>
</form>

OnlineBookShopMvc/Views/Order/CheckoutComplete.cshtml
@model OnlineBookShopMvc.Models.Order;


<h1>Thanks you for Order!</h1>


		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>Book</th>
					<th>Price  | Over all price</th>
					<th>Quantity</th>
				</tr>
			</thead>
			<tbody>
			@foreach (var item in Model.OrderItems)
			{
			var itemTotal = item.Book.Price * item.Quantity;
			var itemTotalOverAll = (item.Book.Price - (item.Book.Price * item.Book.Discount / 100)) * item.Quantity;
						<tr>
							<td>
								<a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.Id"><img src="@item.Book.ImageUrl" style="height: 4em"> </a>
							</td>
							<td>
								<a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.Id">@item.Book.Name</a>
							</td>
							<td>
								@itemTotal.ToString()  | @itemTotalOverAll.ToString();
							</td>
							<td>
								@item.Quantity
							</td>

						</tr>
			}
			</tbody>
			<tfoot>
				<td></td>
				<td class="text-right">
					<strong>
						Total:
					</strong>
				</td>
				<td>
					<strong>
					@Model?.OrderTotal.ToString("c")
					</strong>
				</td>

			</tfoot>
		</table>
			